# Generated by Django 5.2.8 on 2026-02-07 14:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_webhookevent_remove_payment_stripe_charge_id_and_more'),
        ('subscriptions', '0003_rename_stripe_subscription_id_subscription_razorpay_subscription_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique invoice number (e.g., INV-2026-00001)', max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('payment', 'One-time Payment'), ('subscription', 'Subscription Billing'), ('refund', 'Refund')], default='payment', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20)),
                ('bill_to_name', models.CharField(help_text='Customer name', max_length=200)),
                ('bill_to_email', models.EmailField(help_text='Customer email', max_length=254)),
                ('bill_to_phone', models.CharField(blank=True, max_length=20)),
                ('bill_to_address', models.TextField(blank=True, help_text='Customer billing address')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate in percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final amount to be paid', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('paid_date', models.DateTimeField(blank=True, help_text='Date when payment was received', null=True)),
                ('description', models.TextField(blank=True, help_text='Invoice description or notes')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for customer')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF invoice', null=True, upload_to='invoices/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_history', models.ForeignKey(blank=True, help_text='Related billing history entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.billinghistory')),
                ('payment', models.ForeignKey(blank=True, help_text='Related payment transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='payments.payment')),
                ('subscription', models.ForeignKey(blank=True, help_text='Related subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Item description', max_length=500)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount (quantity * unit_price)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.invoice')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='payments_in_invoice_3fa711_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='payments_in_user_id_a545de_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='payments_in_invoice_44e5b3_idx'),
        ),
    ]
