# Generated by Django 5.2.8 on 2025-12-06 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the person contacting', max_length=100)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('message', models.TextField(help_text='Message content', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False, help_text='Has this contact been responded to?')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('PhD', 'PhD')], max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('visa_status', models.CharField(choices=[('F1-OPT', 'F1-OPT'), ('F1-CPT', 'F1-CPT'), ('H1B', 'H1B'), ('Green Card', 'Green Card'), ('Citizen', 'Citizen'), ('Other', 'Other')], max_length=20)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('opt_end_date', models.DateField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='interest_resumes/')),
                ('referral_source', models.CharField(blank=True, choices=[('Google', 'Google'), ('LinkedIn', 'LinkedIn'), ('Friend', 'Friend'), ('University', 'University'), ('Other', 'Other')], max_length=20, null=True)),
                ('consent_to_terms', models.BooleanField()),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('github_url', models.URLField(blank=True, max_length=255, null=True)),
                ('additional_notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('university', models.CharField(blank=True, max_length=100)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('visa_status', models.CharField(blank=True, max_length=50)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('opt_end_date', models.DateField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('consent_to_terms', models.BooleanField(default=False)),
                ('referral_source', models.CharField(blank=True, choices=[('Google', 'Google'), ('LinkedIn', 'LinkedIn'), ('Friend', 'Friend'), ('University', 'University'), ('Other', 'Other')], max_length=20, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('github_url', models.URLField(blank=True, max_length=255, null=True)),
                ('additional_notes', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
