# Generated by Django 5.2.8 on 2026-01-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_status',
            field=models.CharField(choices=[('open', 'Open - Awaiting Admin Review'), ('approved', 'Approved - Ready for Payment'), ('ready_to_assign', 'Ready to Assign - Payment Completed'), ('assigned', 'Assigned - Recruiter Assigned'), ('waiting_payment', 'Waiting for Payment - Payment Expired'), ('closed', 'Closed - Candidate Placed'), ('rejected', 'Rejected - Admin Rejected')], default='open', help_text='Current status in the registration and assignment workflow', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Admin notes about status changes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last status update timestamp'),
        ),
    ]
