# Generated by Django 5.2.8 on 2025-11-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the person contacting', max_length=100)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('message', models.TextField(help_text='Message content', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False, help_text='Has this contact been responded to?')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
