# Generated migration for ClientIntakeSheet and CredentialSheet models

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_registration_status_profile_status_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIntakeSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('marketing_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('marketing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_address', models.TextField()),
                ('mailing_address', models.TextField()),
                ('visa_status', models.CharField(choices=[('F1-OPT', 'F1-OPT'), ('H1B', 'H1B'), ('H4 EAD', 'H4 EAD'), ('Green Card', 'Green Card'), ('US Citizen', 'US Citizen'), ('Other', 'Other')], max_length=50)),
                ('first_entry_us', models.DateField()),
                ('total_years_in_us', models.IntegerField()),
                ('skilled_in', models.TextField()),
                ('currently_learning', models.TextField()),
                ('experienced_with', models.TextField()),
                ('learning_tools', models.TextField()),
                ('non_technical_skills', models.TextField()),
                ('job_1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_1_company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_1_address', models.CharField(blank=True, max_length=255, null=True)),
                ('job_1_start_date', models.DateField(blank=True, null=True)),
                ('job_1_end_date', models.DateField(blank=True, null=True)),
                ('job_1_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship')], max_length=50, null=True)),
                ('job_1_responsibilities', models.TextField(blank=True, null=True)),
                ('job_2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_2_company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_2_address', models.CharField(blank=True, max_length=255, null=True)),
                ('job_2_start_date', models.DateField(blank=True, null=True)),
                ('job_2_end_date', models.DateField(blank=True, null=True)),
                ('job_2_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship')], max_length=50, null=True)),
                ('job_2_responsibilities', models.TextField(blank=True, null=True)),
                ('job_3_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_3_company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_3_address', models.CharField(blank=True, max_length=255, null=True)),
                ('job_3_start_date', models.DateField(blank=True, null=True)),
                ('job_3_end_date', models.DateField(blank=True, null=True)),
                ('job_3_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship')], max_length=50, null=True)),
                ('job_3_responsibilities', models.TextField(blank=True, null=True)),
                ('highest_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('highest_university', models.CharField(blank=True, max_length=255, null=True)),
                ('highest_country', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_graduation_date', models.DateField(blank=True, null=True)),
                ('bachelors_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('bachelors_field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('bachelors_university', models.CharField(blank=True, max_length=255, null=True)),
                ('bachelors_country', models.CharField(blank=True, max_length=100, null=True)),
                ('bachelors_graduation_date', models.DateField(blank=True, null=True)),
                ('certification_name', models.CharField(blank=True, max_length=255, null=True)),
                ('issuing_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='users/documents/passports/')),
                ('government_id_file', models.FileField(blank=True, null=True, upload_to='users/documents/ids/')),
                ('visa_file', models.FileField(blank=True, null=True, upload_to='users/documents/visas/')),
                ('work_authorization_file', models.FileField(blank=True, null=True, upload_to='users/documents/work_authorization/')),
                ('desired_job_role', models.CharField(blank=True, max_length=255, null=True)),
                ('desired_years_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='users/documents/resumes/')),
                ('submission_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('form_submitted_date', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_intake_sheet', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CredentialSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('personal_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('bachelor_graduation_date', models.DateField()),
                ('first_entry_us', models.DateField()),
                ('masters_graduation_date', models.DateField(blank=True, null=True)),
                ('opt_start_date', models.DateField(blank=True, null=True)),
                ('opt_offer_letter_submitted', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('opt_offer_letter_file', models.FileField(blank=True, null=True, upload_to='users/credentials/opt_letters/')),
                ('preferred_job_roles', models.TextField()),
                ('preferred_locations', models.TextField()),
                ('linkedin_username', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_password', models.CharField(blank=True, max_length=255, null=True)),
                ('indeed_username', models.CharField(blank=True, max_length=255, null=True)),
                ('indeed_password', models.CharField(blank=True, max_length=255, null=True)),
                ('dice_username', models.CharField(blank=True, max_length=255, null=True)),
                ('dice_password', models.CharField(blank=True, max_length=255, null=True)),
                ('monster_username', models.CharField(blank=True, max_length=255, null=True)),
                ('monster_password', models.CharField(blank=True, max_length=255, null=True)),
                ('ziprecruiter_username', models.CharField(blank=True, max_length=255, null=True)),
                ('ziprecruiter_password', models.CharField(blank=True, max_length=255, null=True)),
                ('glassdoor_username', models.CharField(blank=True, max_length=255, null=True)),
                ('glassdoor_password', models.CharField(blank=True, max_length=255, null=True)),
                ('buildin_username', models.CharField(blank=True, max_length=255, null=True)),
                ('buildin_password', models.CharField(blank=True, max_length=255, null=True)),
                ('jobvite_username', models.CharField(blank=True, max_length=255, null=True)),
                ('jobvite_password', models.CharField(blank=True, max_length=255, null=True)),
                ('careerbuilder_username', models.CharField(blank=True, max_length=255, null=True)),
                ('careerbuilder_password', models.CharField(blank=True, max_length=255, null=True)),
                ('github_username', models.CharField(blank=True, max_length=255, null=True)),
                ('github_password', models.CharField(blank=True, max_length=255, null=True)),
                ('other_job_platform_accounts', models.TextField(blank=True, null=True)),
                ('submission_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('form_submitted_date', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential_sheet', to='users.profile')),
            ],
        ),
    ]
