# Generated by Django 5.2.8 on 2026-01-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientintakesheet_credentialsheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientintakesheet',
            options={'ordering': ['-submission_timestamp'], 'verbose_name': 'Client Intake Sheet', 'verbose_name_plural': 'Client Intake Sheets'},
        ),
        migrations.AlterModelOptions(
            name='credentialsheet',
            options={'ordering': ['-submission_timestamp'], 'verbose_name': 'Credential Sheet', 'verbose_name_plural': 'Credential Sheets'},
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='alternate_email',
            field=models.EmailField(blank=True, help_text='Alternate Email Address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='bachelors_country',
            field=models.CharField(blank=True, help_text='Country', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='bachelors_degree',
            field=models.CharField(blank=True, choices=[("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Other', 'Other')], help_text="Bachelor's Degree", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='bachelors_field_of_study',
            field=models.CharField(blank=True, help_text='Field of Study', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='bachelors_graduation_date',
            field=models.DateField(blank=True, help_text='Graduation Date', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='bachelors_university',
            field=models.CharField(blank=True, help_text='University/Institution Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='certification_name',
            field=models.CharField(blank=True, help_text='Certification Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='current_address',
            field=models.TextField(help_text='Current Address'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='currently_learning',
            field=models.TextField(blank=True, help_text='Currently Learning / Recently Learned', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='date_of_birth',
            field=models.DateField(help_text='Date of Birth (DD/MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='desired_job_role',
            field=models.CharField(blank=True, help_text='Desired Job Role / Roles', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='desired_years_experience',
            field=models.CharField(blank=True, help_text='Desired years of experience', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='email',
            field=models.EmailField(help_text='Email Address', max_length=254),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='experienced_with',
            field=models.TextField(help_text='Experienced With (e.g., AWS, SQL, Docker, Git, Selenium, etc.)'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='first_entry_us',
            field=models.DateField(help_text='First Entry into the U.S. (DD/MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='form_submitted_date',
            field=models.DateTimeField(blank=True, help_text='Date when form was first submitted', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='government_id_file',
            field=models.FileField(blank=True, help_text='Government ID (DL / State ID)', null=True, upload_to='users/documents/ids/'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='highest_country',
            field=models.CharField(blank=True, help_text='Country', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='highest_degree',
            field=models.CharField(blank=True, choices=[("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Other', 'Other')], help_text='Highest Degree', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='highest_field_of_study',
            field=models.CharField(blank=True, help_text='Field of Study', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='highest_graduation_date',
            field=models.DateField(blank=True, help_text='Graduation Date', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='highest_university',
            field=models.CharField(blank=True, help_text='University/Institution Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='Whether form can be edited after submission'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='issued_date',
            field=models.DateField(blank=True, help_text='Issued Date', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='issuing_organization',
            field=models.CharField(blank=True, help_text='Issuing Organization', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_1_address',
            field=models.TextField(blank=True, help_text='Company Address', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_1_company',
            field=models.CharField(blank=True, help_text='Company Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_1_end_date',
            field=models.DateField(blank=True, help_text='End Date (DD/MM/YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_1_responsibilities',
            field=models.TextField(blank=True, help_text='Key Responsibilities / Projects', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_1_start_date',
            field=models.DateField(blank=True, help_text='Start Date (DD/MM/YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_1_title',
            field=models.CharField(blank=True, help_text='Job Title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_1_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship')], help_text='Job Type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_2_address',
            field=models.TextField(blank=True, help_text='Company Address', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_2_company',
            field=models.CharField(blank=True, help_text='Company Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_2_end_date',
            field=models.DateField(blank=True, help_text='End Date (DD/MM/YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_2_responsibilities',
            field=models.TextField(blank=True, help_text='Key Responsibilities / Projects', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_2_start_date',
            field=models.DateField(blank=True, help_text='Start Date (DD/MM/YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_2_title',
            field=models.CharField(blank=True, help_text='Job Title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_2_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship')], help_text='Job Type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_3_address',
            field=models.TextField(blank=True, help_text='Company Address', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_3_company',
            field=models.CharField(blank=True, help_text='Company Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_3_end_date',
            field=models.DateField(blank=True, help_text='End Date (DD/MM/YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_3_responsibilities',
            field=models.TextField(blank=True, help_text='Key Responsibilities / Projects', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_3_start_date',
            field=models.DateField(blank=True, help_text='Start Date (DD/MM/YYYY)', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_3_title',
            field=models.CharField(blank=True, help_text='Job Title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='job_3_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship')], help_text='Job Type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='learning_tools',
            field=models.TextField(blank=True, help_text='Learning Now / Self-Taught Tools', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='mailing_address',
            field=models.TextField(help_text='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='marketing_contact_number',
            field=models.CharField(blank=True, help_text='Contact number for Marketing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='marketing_email',
            field=models.EmailField(blank=True, help_text='Email for Marketing', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='non_technical_skills',
            field=models.TextField(blank=True, help_text='Other Non Technical Skills / Courses (e.g., Business Analysis, Digital Marketing, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='passport_file',
            field=models.FileField(blank=True, help_text='Passport', null=True, upload_to='users/documents/passports/'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='phone_number',
            field=models.CharField(help_text='Phone Number with country code', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Original Resume', null=True, upload_to='users/documents/resumes/'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='skilled_in',
            field=models.TextField(help_text='Skilled In (e.g., Python, Java, C++, JavaScript, React, Node.js, etc.)'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='submission_timestamp',
            field=models.DateTimeField(blank=True, help_text='Form submission timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='total_years_in_us',
            field=models.IntegerField(help_text='Total Years in the U.S.'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='visa_file',
            field=models.FileField(blank=True, help_text='Visa', null=True, upload_to='users/documents/visas/'),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='visa_status',
            field=models.CharField(choices=[('F1-OPT', 'F1-OPT'), ('H1B', 'H1B'), ('H4 EAD', 'H4 EAD'), ('Green Card', 'Green Card'), ('US Citizen', 'US Citizen'), ('Other', 'Other')], help_text='Current Visa Status', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientintakesheet',
            name='work_authorization_file',
            field=models.FileField(blank=True, help_text='Work Authorization Proof (OPT Card, EAD, etc.)', null=True, upload_to='users/documents/work_authorization/'),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='bachelor_graduation_date',
            field=models.DateField(help_text='Bachelors Graduation Date'),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='buildin_password',
            field=models.CharField(blank=True, help_text='BuildIn Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='buildin_username',
            field=models.CharField(blank=True, help_text='BuildIn Login ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='careerbuilder_password',
            field=models.CharField(blank=True, help_text='CareerBuilder Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='careerbuilder_username',
            field=models.CharField(blank=True, help_text='CareerBuilder Login ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='dice_password',
            field=models.CharField(blank=True, help_text='Dice Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='dice_username',
            field=models.CharField(blank=True, help_text='Dice Login ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='first_entry_us',
            field=models.DateField(help_text='First Entry into the U.S. (DD/MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='form_submitted_date',
            field=models.DateTimeField(blank=True, help_text='Date when form was first submitted', null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='full_name',
            field=models.CharField(help_text='Full Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='github_password',
            field=models.CharField(blank=True, help_text='GitHub Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub Login ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='glassdoor_password',
            field=models.CharField(blank=True, help_text='Glassdoor Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='glassdoor_username',
            field=models.CharField(blank=True, help_text='Glassdoor Login ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='indeed_password',
            field=models.CharField(blank=True, help_text='Indeed Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='indeed_username',
            field=models.CharField(blank=True, help_text='Indeed Login ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='Whether form can be edited after submission'),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='jobvite_password',
            field=models.CharField(blank=True, help_text='Jobvite Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='jobvite_username',
            field=models.CharField(blank=True, help_text='Jobvite Login ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='linkedin_password',
            field=models.CharField(blank=True, help_text='LinkedIn Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='linkedin_username',
            field=models.CharField(blank=True, help_text='LinkedIn Login ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='location',
            field=models.CharField(help_text='Location (City, State)', max_length=100),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='masters_graduation_date',
            field=models.DateField(blank=True, help_text='Masters Graduation Date', null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='monster_password',
            field=models.CharField(blank=True, help_text='Monster Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='monster_username',
            field=models.CharField(blank=True, help_text='Monster Login ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='opt_offer_letter_file',
            field=models.FileField(blank=True, help_text='Upload Offer letter', null=True, upload_to='users/credentials/opt_letters/'),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='opt_offer_letter_submitted',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='OPT offer letter submitted', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='opt_start_date',
            field=models.DateField(blank=True, help_text='OPT Start date', null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='other_job_platform_accounts',
            field=models.TextField(blank=True, help_text='Mention all other Job Platform accounts you have (or N/A)', null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='personal_email',
            field=models.EmailField(help_text='Personal Email Address', max_length=254),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='phone_number',
            field=models.CharField(help_text='Phone Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='preferred_job_roles',
            field=models.TextField(help_text='Preferred Job Roles for marketing'),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='preferred_locations',
            field=models.TextField(help_text='Preferred Location(s)'),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='submission_timestamp',
            field=models.DateTimeField(blank=True, help_text='Form submission timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='ziprecruiter_password',
            field=models.CharField(blank=True, help_text='ZipRecruiter Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentialsheet',
            name='ziprecruiter_username',
            field=models.CharField(blank=True, help_text='ZipRecruiter Login ID', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='clientintakesheet',
            index=models.Index(fields=['email'], name='users_clien_email_99299b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientintakesheet',
            index=models.Index(fields=['submission_timestamp'], name='users_clien_submiss_ff48bf_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialsheet',
            index=models.Index(fields=['personal_email'], name='users_crede_persona_aaab1b_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialsheet',
            index=models.Index(fields=['submission_timestamp'], name='users_crede_submiss_d27b45_idx'),
        ),
    ]
