# Generated by Django 5.2.8 on 2026-03-19 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_type', models.CharField(default='subscription', max_length=50)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_name', models.CharField(max_length=255)),
                ('charge_type', models.CharField(choices=[('monthly_service_fee', 'Monthly Service Fee'), ('mock_practice_fee', 'Mock Practice Fee'), ('interview_support_fee', 'Interview Support Fee'), ('operations_support_fee', 'Operations Support Fee'), ('other', 'Other')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived'), ('partially_paid', 'Partially Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('is_internal_note', models.BooleanField(default=False)),
                ('previous_due_date', models.DateField(blank=True, null=True)),
                ('due_date_change_reason', models.TextField(blank=True, null=True)),
                ('due_date_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_line_items',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(default='Standard Marketing Plan', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('grace_period', 'Grace Period'), ('paused', 'Paused')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('next_billing_at', models.DateField(blank=True, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('grace_days', models.IntegerField(default=5)),
                ('grace_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('billing_method_brand', models.CharField(blank=True, max_length=30, null=True)),
                ('billing_method_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('billing_method_exp_month', models.CharField(blank=True, max_length=2, null=True)),
                ('billing_method_exp_year', models.CharField(blank=True, max_length=4, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
