# Generated by Django 5.2.8 on 2026-02-22 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(help_text='Job role title (e.g., Software Engineer, Data Analyst)', max_length=200)),
                ('role_category', models.CharField(blank=True, help_text='Optional category (e.g., Engineering, Data Science)', max_length=100)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on why this role is suggested')),
                ('is_selected', models.BooleanField(default=False, help_text='User selected this role as desired')),
                ('selected_at', models.DateTimeField(blank=True, help_text='When user selected this role', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(help_text='Admin who added this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_role_suggestions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Suggestion',
                'verbose_name_plural': 'Role Suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='jobs_userro_user_id_b502b0_idx'), models.Index(fields=['is_selected'], name='jobs_userro_is_sele_d10ef0_idx'), models.Index(fields=['role_category'], name='jobs_userro_role_ca_798d1a_idx')],
            },
        ),
    ]
