# Generated by Django 5.2.8 on 2026-02-07 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Job role title (e.g., Software Engineer, Data Analyst)', max_length=200, unique=True)),
                ('category', models.CharField(help_text='Category (e.g., Engineering, Data Science, Marketing)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills (e.g., ["Python", "Django", "REST API"])')),
                ('preferred_skills', models.JSONField(default=list, help_text='List of preferred/nice-to-have skills')),
                ('min_years_experience', models.IntegerField(default=0, help_text='Minimum years of experience')),
                ('max_years_experience', models.IntegerField(blank=True, help_text='Maximum years of experience', null=True)),
                ('required_degrees', models.JSONField(default=list, help_text='Required degrees (e.g., ["Bachelor\'s", "Master\'s"])')),
                ('alternative_titles', models.JSONField(default=list, help_text='Alternative job titles (e.g., ["SWE", "Software Dev"])')),
                ('avg_salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Average minimum salary', max_digits=10, null=True)),
                ('avg_salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Average maximum salary', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active for recommendations')),
                ('popularity_score', models.IntegerField(default=0, help_text='Popularity score (higher = more common)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'ordering': ['-popularity_score', 'title'],
                'indexes': [models.Index(fields=['category'], name='jobs_jobrol_categor_cd2a6a_idx'), models.Index(fields=['is_active', '-popularity_score'], name='jobs_jobrol_is_acti_367afc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRoleRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=2, help_text='Match score (0-100)', max_digits=5)),
                ('skill_match_score', models.DecimalField(decimal_places=2, default=0, help_text='Skills match score', max_digits=5)),
                ('experience_match_score', models.DecimalField(decimal_places=2, default=0, help_text='Experience match score', max_digits=5)),
                ('education_match_score', models.DecimalField(decimal_places=2, default=0, help_text='Education match score', max_digits=5)),
                ('matched_skills', models.JSONField(default=list, help_text='List of matched skills')),
                ('missing_skills', models.JSONField(default=list, help_text='List of missing required skills')),
                ('recommendation_reason', models.TextField(blank=True, help_text='Explanation for why this role is recommended')),
                ('is_interested', models.BooleanField(default=False, help_text='User indicated interest')),
                ('is_dismissed', models.BooleanField(default=False, help_text='User dismissed this recommendation')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When user viewed this recommendation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.jobrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Recommendation',
                'verbose_name_plural': 'User Role Recommendations',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_relevant', 'Not Relevant'), ('too_senior', 'Too Senior'), ('too_junior', 'Too Junior'), ('wrong_skills', 'Wrong Skills'), ('wrong_location', 'Wrong Location'), ('other', 'Other')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optional user comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='jobs.userrolerecommendation')),
            ],
            options={
                'verbose_name': 'Recommendation Feedback',
                'verbose_name_plural': 'Recommendation Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_skills', models.JSONField(default=list, help_text='Primary/expert skills')),
                ('secondary_skills', models.JSONField(default=list, help_text='Secondary/intermediate skills')),
                ('learning_skills', models.JSONField(default=list, help_text='Currently learning')),
                ('total_years_experience', models.DecimalField(decimal_places=1, default=0, help_text='Total years of professional experience', max_digits=4)),
                ('industries', models.JSONField(default=list, help_text='Industries worked in')),
                ('highest_degree', models.CharField(blank=True, max_length=50)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('desired_roles', models.JSONField(default=list, help_text='User-specified desired roles')),
                ('preferred_locations', models.JSONField(default=list, help_text='Preferred work locations')),
                ('job_type_preference', models.CharField(blank=True, help_text='Full-time, Part-time, Internship, etc.', max_length=50)),
                ('profile_completeness', models.IntegerField(default=0, help_text='Profile completeness percentage (0-100)')),
                ('last_updated_from_intake', models.DateTimeField(blank=True, help_text='Last sync from intake sheet', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill Profile',
                'verbose_name_plural': 'User Skill Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='userrolerecommendation',
            index=models.Index(fields=['user', '-match_score'], name='jobs_userro_user_id_94a797_idx'),
        ),
        migrations.AddIndex(
            model_name='userrolerecommendation',
            index=models.Index(fields=['is_interested'], name='jobs_userro_is_inte_c39cb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrolerecommendation',
            unique_together={('user', 'role')},
        ),
    ]
