# Generated by Django 5.2.8 on 2026-02-22 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_userrolesuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrolesuggestion',
            name='jobs_userro_is_sele_d10ef0_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrolesuggestion',
            name='jobs_userro_role_ca_798d1a_idx',
        ),
        migrations.AddField(
            model_name='userrolesuggestion',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrolesuggestion',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_role_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrolesuggestion',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userrolesuggestion',
            name='is_selected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userrolesuggestion',
            name='role_category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userrolesuggestion',
            name='role_title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userrolesuggestion',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userrolesuggestion',
            unique_together={('user', 'role_title')},
        ),
        migrations.AddIndex(
            model_name='userrolesuggestion',
            index=models.Index(fields=['user', 'is_selected'], name='jobs_userro_user_id_59f151_idx'),
        ),
        migrations.AddIndex(
            model_name='userrolesuggestion',
            index=models.Index(fields=['submitted_at'], name='jobs_userro_submitt_6d878c_idx'),
        ),
    ]
