# Generated by Django 5.2.8 on 2025-12-08 09:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(help_text='Unique employee ID (e.g., REC001)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name', max_length=100)),
                ('email', models.EmailField(help_text='Company email address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('department', models.CharField(choices=[('it_staffing', 'IT Staffing'), ('healthcare_staffing', 'Healthcare Staffing'), ('finance_staffing', 'Finance Staffing'), ('engineering_staffing', 'Engineering Staffing'), ('general', 'General Recruitment')], default='it_staffing', help_text='Department', max_length=50)),
                ('specialization', models.CharField(choices=[('software_dev', 'Software Development'), ('data_science', 'Data Science/Analytics'), ('cloud_devops', 'Cloud/DevOps'), ('cybersecurity', 'Cybersecurity'), ('network_admin', 'Network Administration'), ('database_admin', 'Database Administration'), ('qa_testing', 'QA/Testing'), ('ui_ux', 'UI/UX Design'), ('project_management', 'Project Management'), ('business_analysis', 'Business Analysis'), ('general_it', 'General IT')], default='general_it', help_text='Primary specialization area', max_length=50)),
                ('date_of_joining', models.DateField(help_text='Employment start date')),
                ('max_clients', models.IntegerField(default=3, help_text='Maximum number of clients that can be assigned (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('current_clients_count', models.IntegerField(default=0, help_text='Current number of assigned clients')),
                ('total_placements', models.IntegerField(default=0, help_text='Total successful job placements', validators=[django.core.validators.MinValueValidator(0)])),
                ('active_applications', models.IntegerField(default=0, help_text='Number of currently active job applications', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', help_text='Account status', max_length=20)),
                ('active', models.BooleanField(default=False, help_text='Whether recruiter account is active (approved by admin)')),
                ('verified', models.BooleanField(default=False, help_text='Email/identity verified')),
                ('company_name', models.CharField(default='Hyrind Recruitment Services', help_text='Company/Agency name', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this recruiter', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(help_text='Associated user profile', on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to='users.profile')),
            ],
            options={
                'verbose_name': 'Recruiter',
                'verbose_name_plural': 'Recruiters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active - In Progress'), ('placed', 'Successfully Placed'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', help_text='Assignment status', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', help_text='Assignment priority level', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the assignment was created')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('placement_date', models.DateField(blank=True, help_text='Date when client was successfully placed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Assignment notes and special instructions', null=True)),
                ('internal_comments', models.TextField(blank=True, help_text='Internal comments (not visible to client)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(help_text='Client candidate profile', on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='users.profile')),
                ('recruiter', models.ForeignKey(help_text='Assigned recruiter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='recruiters.recruiter')),
            ],
            options={
                'verbose_name': 'Client Assignment',
                'verbose_name_plural': 'Client Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full legal name', max_length=100)),
                ('email', models.EmailField(help_text='Email address for communication', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Primary phone number (10-12 digits)', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number (optional)', max_length=20, null=True)),
                ('date_of_joining', models.DateField(help_text='Employment start date')),
                ('date_of_birth', models.DateField(help_text='Date of birth (DD/MM/YYYY)')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Gender', max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Marital status', max_length=20)),
                ('father_name', models.CharField(help_text="Father's full name", max_length=100)),
                ('mother_name', models.CharField(help_text="Mother's full name", max_length=100)),
                ('spouse_name', models.CharField(blank=True, help_text="Spouse's name (if married)", max_length=100, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown / Not provided')], help_text='Blood group', max_length=20)),
                ('emergency_contact_number', models.CharField(help_text='Emergency contact number', max_length=20)),
                ('permanent_address', models.TextField(help_text='Full permanent address')),
                ('correspondence_address', models.TextField(blank=True, help_text='Mailing address (leave blank if same as permanent)', null=True)),
                ('same_as_permanent_address', models.BooleanField(default=True, help_text='Is correspondence address same as permanent?')),
                ('aadhaar_number', models.CharField(help_text='Aadhaar number (12 digits)', max_length=14, unique=True)),
                ('aadhaar_card_file', models.FileField(blank=True, help_text='Aadhaar card scan (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/aadhaar/')),
                ('pan_number', models.CharField(help_text='PAN number (10 alphanumeric)', max_length=10, unique=True)),
                ('pan_card_file', models.FileField(blank=True, help_text='PAN card scan (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/pan/')),
                ('passport_number', models.CharField(blank=True, help_text='Passport number (optional)', max_length=20, null=True)),
                ('passport_copy_file', models.FileField(blank=True, help_text='Passport copy (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/passport/')),
                ('address_proof_file', models.FileField(blank=True, help_text='Address proof document (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/address_proof/')),
                ('highest_education', models.CharField(help_text='Highest qualification (e.g., Bachelor of Science)', max_length=100)),
                ('year_of_graduation', models.PositiveIntegerField(help_text='Year of graduation (YYYY)')),
                ('course', models.CharField(help_text='Course/Major name', max_length=100)),
                ('degree_certificate_file', models.FileField(blank=True, help_text='Degree certificate (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/degree_certificates/')),
                ('bank_name', models.CharField(help_text='Bank name', max_length=100)),
                ('account_holder_name', models.CharField(help_text='Account holder name (as per bank records)', max_length=100)),
                ('bank_account_number', models.CharField(help_text='Bank account number', max_length=50)),
                ('ifsc_code', models.CharField(help_text='IFSC code (11 characters)', max_length=20)),
                ('branch_name', models.CharField(help_text='Bank branch name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Has admin verified this registration?')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='recruiters__email_c981d7_idx'), models.Index(fields=['aadhaar_number'], name='recruiters__aadhaar_252a54_idx'), models.Index(fields=['pan_number'], name='recruiters__pan_num_34e4a9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='recruiter',
            index=models.Index(fields=['email'], name='recruiters__email_f8f01d_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiter',
            index=models.Index(fields=['employee_id'], name='recruiters__employe_9090a4_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiter',
            index=models.Index(fields=['status', 'active'], name='recruiters__status_14b324_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'priority'], name='recruiters__status_94c278_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_at'], name='recruiters__assigne_58dfe1_idx'),
        ),
    ]
