# Generated by Django 5.2.8 on 2026-03-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_initial'),
        ('recruiters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysubmissionlog',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='submission_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_entries', to='recruiters.dailysubmissionlog'),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_entries_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterassignment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='recruiterassignment',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterbankdetail',
            name='recruiter',
            field=models.OneToOneField(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailysubmissionlog',
            unique_together={('candidate', 'recruiter', 'log_date')},
        ),
        migrations.AlterUniqueTogether(
            name='recruiterassignment',
            unique_together={('candidate', 'recruiter')},
        ),
    ]
