# Generated by Django 5.2.8 on 2025-12-06 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full legal name', max_length=100)),
                ('email', models.EmailField(help_text='Email address for communication', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Primary phone number (10-12 digits)', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number (optional)', max_length=20, null=True)),
                ('date_of_joining', models.DateField(help_text='Employment start date')),
                ('date_of_birth', models.DateField(help_text='Date of birth (DD/MM/YYYY)')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Gender', max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Marital status', max_length=20)),
                ('father_name', models.CharField(help_text="Father's full name", max_length=100)),
                ('mother_name', models.CharField(help_text="Mother's full name", max_length=100)),
                ('spouse_name', models.CharField(blank=True, help_text="Spouse's name (if married)", max_length=100, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown / Not provided')], help_text='Blood group', max_length=20)),
                ('emergency_contact_number', models.CharField(help_text='Emergency contact number', max_length=20)),
                ('permanent_address', models.TextField(help_text='Full permanent address')),
                ('correspondence_address', models.TextField(blank=True, help_text='Mailing address (leave blank if same as permanent)', null=True)),
                ('same_as_permanent_address', models.BooleanField(default=True, help_text='Is correspondence address same as permanent?')),
                ('aadhaar_number', models.CharField(help_text='Aadhaar number (12 digits)', max_length=14, unique=True)),
                ('aadhaar_card_file', models.FileField(blank=True, help_text='Aadhaar card scan (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/aadhaar/')),
                ('pan_number', models.CharField(help_text='PAN number (10 alphanumeric)', max_length=10, unique=True)),
                ('pan_card_file', models.FileField(blank=True, help_text='PAN card scan (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/pan/')),
                ('passport_number', models.CharField(blank=True, help_text='Passport number (optional)', max_length=20, null=True)),
                ('passport_copy_file', models.FileField(blank=True, help_text='Passport copy (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/passport/')),
                ('address_proof_file', models.FileField(blank=True, help_text='Address proof document (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/address_proof/')),
                ('highest_education', models.CharField(help_text='Highest qualification (e.g., Bachelor of Science)', max_length=100)),
                ('year_of_graduation', models.PositiveIntegerField(help_text='Year of graduation (YYYY)')),
                ('course', models.CharField(help_text='Course/Major name', max_length=100)),
                ('degree_certificate_file', models.FileField(blank=True, help_text='Degree certificate (PDF, JPG, PNG - optional)', null=True, upload_to='recruiters/degree_certificates/')),
                ('bank_name', models.CharField(help_text='Bank name', max_length=100)),
                ('account_holder_name', models.CharField(help_text='Account holder name (as per bank records)', max_length=100)),
                ('bank_account_number', models.CharField(help_text='Bank account number', max_length=50)),
                ('ifsc_code', models.CharField(help_text='IFSC code (11 characters)', max_length=20)),
                ('branch_name', models.CharField(help_text='Bank branch name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Has admin verified this registration?')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='recruiters__email_c981d7_idx'), models.Index(fields=['aadhaar_number'], name='recruiters__aadhaar_252a54_idx'), models.Index(fields=['pan_number'], name='recruiters__pan_num_34e4a9_idx')],
            },
        ),
    ]
