# Generated by Django 5.2.8 on 2026-02-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_assignment_multiple_recruiters'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reassigned_from',
            field=models.ForeignKey(blank=True, help_text='Original assignment this was reassigned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments', to='recruiters.assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reassignment_reason',
            field=models.TextField(blank=True, help_text='Reason for reassignment (e.g., recruiter absent, workload rebalancing)', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary Recruiter'), ('secondary', 'Secondary Recruiter'), ('team_lead', 'Team Lead'), ('backup', 'Backup / Cover')], default='primary', help_text='Recruiter role on this assignment (primary, secondary, team_lead, backup)', max_length=20),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('busy', 'Fully Occupied')], default='available', help_text='Current availability for accepting new clients', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active - In Progress'), ('placed', 'Successfully Placed'), ('on_hold', 'On Hold'), ('reassigned', 'Reassigned to Another Recruiter'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', help_text='Assignment status', max_length=20),
        ),
    ]
