# Generated by Django 5.2.8 on 2026-03-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credentialversion',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='credentialversion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewlog',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_logs', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='interviewlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewlog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementclosure',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='placementclosure',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='rolesuggestion',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_suggestions', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='rolesuggestion',
            name='suggested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
