# Generated by Django 5.2.8 on 2026-03-19 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cal_training_url', models.URLField(blank=True, help_text='Schedule Training Practice URL', null=True)),
                ('cal_mock_practice_url', models.URLField(blank=True, help_text='Schedule Mock Practice Call URL', null=True)),
                ('cal_interview_training_url', models.URLField(blank=True, help_text='Schedule Interview Training URL', null=True)),
                ('cal_interview_support_url', models.URLField(blank=True, help_text='Schedule Interview Support URL', null=True)),
                ('cal_operations_call_url', models.URLField(blank=True, help_text='Schedule Operations Call URL', null=True)),
                ('review_timeline_text', models.CharField(default='24–48 hours', help_text="Review timeline shown to candidates (e.g. '24–48 hours')", max_length=100)),
                ('roles_locked_message', models.TextField(blank=True, help_text='Message on Roles tab before roles are published', null=True)),
                ('credentials_locked_message', models.TextField(blank=True, help_text='Message on Credentials tab when locked', null=True)),
                ('help_desk_url', models.URLField(blank=True, help_text='Support / Help Desk URL', null=True)),
                ('grace_period_days', models.IntegerField(default=5, help_text='Grace period in days before billing suspension')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Configuration',
                'verbose_name_plural': 'Admin Configuration',
                'db_table': 'admin_config',
            },
        ),
    ]
