# Generated by Django 5.2.8 on 2025-12-19 05:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Profile Marketing Services Fee, Skill Development Training', max_length=200, unique=True)),
                ('plan_type', models.CharField(choices=[('base', 'Base Subscription'), ('addon', 'Add-on Service')], default='addon', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this plan includes')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in USD. For add-ons, this is the default price (can be customized per user)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_mandatory', models.BooleanField(default=False, help_text='If true, all users must have this plan')),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans can be assigned to users')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One-Time')], default='monthly', max_length=20)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['plan_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription (Legacy)', 'verbose_name_plural': 'Subscriptions (Legacy)'},
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Actual price for this user (may differ from base price for add-ons)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('pending', 'Pending Payment'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='inactive', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When subscription became active', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When subscription was cancelled/expired', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin reference')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.profile')),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to='subscriptions.usersubscription')),
            ],
            options={
                'verbose_name': 'Billing History',
                'verbose_name_plural': 'Billing History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('profile', 'plan'), name='unique_active_subscription_per_plan'),
        ),
    ]
