# Generated by Django 5.2.8 on 2025-12-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='razorpay_subscription_id',
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='stripe_payment_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, help_text='Razorpay subscription ID', max_length=100, null=True),
        ),
    ]
